# Generated by Django 4.1.4 on 2023-04-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('colour', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('img', models.URLField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
    ]
