# Generated by Django 4.1.4 on 2023-04-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_cartitem_added_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='added_at',
        ),
    ]
