# Generated by Django 4.1.4 on 2023-04-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_remove_product_brand_remove_product_colour_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
