# Generated by Django 4.1.4 on 2023-04-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='CartItems',
        ),
    ]
