# Generated by Django 4.1.4 on 2023-04-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_rename_cartitem_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='p_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
