# Generated by Django 4.1.4 on 2023-04-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_cartitems_brand_cartitems_color_cartitems_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='brand',
            field=models.CharField(blank=True, default=0.0, max_length=50),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='color',
            field=models.CharField(blank=True, default=0.0, max_length=50),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='image_url',
            field=models.URLField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='p_id',
            field=models.CharField(blank=True, default=0.0, max_length=50),
        ),
    ]
