# Generated by Django 4.1.4 on 2023-04-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_alter_cartitems_brand_alter_cartitems_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='email',
            field=models.EmailField(blank=True, default=0.0, max_length=50),
        ),
    ]
