# Generated by Django 4.1.4 on 2023-04-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_cartitems_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_status', models.CharField(default='Not shipped yet', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('status', models.CharField(default='Unavailable', max_length=20)),
                ('color', models.CharField(blank=True, default=0.0, max_length=50)),
                ('brand', models.CharField(blank=True, default=0.0, max_length=50)),
                ('p_id', models.CharField(blank=True, default=0.0, max_length=50)),
                ('image_url', models.URLField(blank=True, default=0.0)),
                ('email', models.EmailField(blank=True, default=0.0, max_length=50)),
            ],
        ),
    ]
