# Generated by Django 4.1.4 on 2023-04-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0013_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='email',
        ),
    ]
