# Generated by Django 4.1.4 on 2023-05-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0015_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, default='default.svg', null=True, upload_to='static/'),
        ),
    ]
